# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

## STEP 1: BUILD NUMBER HANDLER
#  desc "increment build number"
#   lane :bump do
#     begin
#       latest_release = firebase_app_distribution_get_latest_release(
#         app: ENV['FIREBASE_APP_ID']
#       )

#       if latest_release && latest_release[:buildVersion]
#         new_build_number = latest_release[:buildVersion].to_i + 1
#       else
#         UI.important("No previous releases found. Starting with build number 1")
#         new_build_number = 1
#       end
#     rescue => e
#       UI.important("Error fetching latest release: #{e.message}")
#       UI.important("Starting with build number 1")
#       new_build_number = 1
#     end

#     flutter_versioner(
#       pubspec_file_path: "../pubspec.yaml",
#       value: new_build_number.to_s,
#       version_component: "version_code"
#     )
#     UI.success("Build number set to: #{new_build_number}")

#     new_build_number
#   end


## STEP 2: DEPLOY APK
  # desc "Deploy on Firebase Distribution"
  # lane :beta do
  #   bump
  #   sh("cd ../../ && flutter build apk --release")

  #   firebase_app_distribution(
  #     app: ENV['FIREBASE_APP_ID'],
  #     groups: "testers",
  #     release_notes: "New Flutter build from Fastlane",
  #     apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
  #   )
  # end
end
